version: '3.8'

services:

  devcontainer:
    image: ${DEVCONTAINER_IMAGE}
    volumes:
      - ../..:/workspaces:cached
      - ${PROGRESS_CFG}:/usr/dlc/progress.cfg
    ports:
      - ${DEBUG_PORT}:3099
    command: sleep infinity

  sports2020-db:
    image: ${DB_IMAGE}
    volumes:
      - ${PROGRESS_CFG}:/usr/dlc/progress.cfg
    ports:
      - 10000-10010:10000-10010
    environment:
      - DBNAME=sports2020    
      
  sports2020-pas:
    image: ${PAS_IMAGE}
    volumes:
      - ${PROGRESS_CFG}:/usr/dlc/progress.cfg
      - ../src:/app/src
      - ../as.pf:/app/config/as.pf
    ports:
      - ${PAS_PORT}:8810
    environment:
      - PASWEBHANDLERS=/app/src/webhandlers/ROOT.handlers
    depends_on:
      - sports2020-db

  plantuml:
    image: plantuml/plantuml-server
    ports:
      - 8080:8080

    